apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab13
  labels:
    app: frontend-lab13
spec:
  selector:
    matchLabels:
      app: frontend-lab13
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab13
    spec:
      containers:
        - name: frontend-lab13
          image: hyukseoung/frontend-lab13
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
